<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOArRGuu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOArRGuu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOArRGuu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOArRGuu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOArRGuu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OArRGuu',
    'container.build_id' => '24c56527',
    'container.build_time' => 1558217217,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOArRGuu');
