<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDRnyfY4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDRnyfY4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDRnyfY4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDRnyfY4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDRnyfY4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DRnyfY4',
    'container.build_id' => 'cbc3808e',
    'container.build_time' => 1560627275,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDRnyfY4');
