<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM0uTxvQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM0uTxvQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM0uTxvQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM0uTxvQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM0uTxvQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M0uTxvQ',
    'container.build_id' => 'edee4374',
    'container.build_time' => 1560807343,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM0uTxvQ');
